update toolkit (#78)
* use latest toolkit
* update packages
* prettier
* update circleci and go modules
* remove vendored modules and update
* add gcs publish

Co-authored-by: Brian Gann <briangann@users.noreply.github.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,7 @@ version: 2.1
 parameters:
   ssh-fingerprint:
     type: string
-    default: "dc:60:ab:c7:2d:8c:82:50:2a:2a:97:1a:c0:66:83:14"
+    default: ${GITHUB_SSH_FINGERPRINT}
 
 aliases:
   # Workflow filters
@@ -32,6 +32,9 @@ workflows:
             - build_frontend
             - build_backend
             - build_docs
+      - publish_artifacts_to_gcs:
+          requires:
+            - package
       - provisioning:
           requires:
             - build_frontend
@@ -59,9 +62,12 @@ executors:
   default_exec: # declares a reusable executor
     docker:
       - image: srclosson/grafana-plugin-ci-alpine:latest
-  e2e_exec: 
+  e2e_exec:
     docker:
       - image: srclosson/grafana-plugin-ci-e2e:latest
+  cloud_sdk_exec:
+    docker:
+      - image: google/cloud-sdk
 
 jobs:
   yarn_install:
@@ -99,7 +105,7 @@ jobs:
       - run:
           name: Build docs
           command: |
-            ./node_modules/.bin/grafana-toolkit plugin:ci-docs
+            /usr/local/bin/grafana-toolkit plugin:ci-docs
             [ -d "dist" ] || circleci-agent step halt
       - persist_to_workspace:
           root: .
@@ -116,7 +122,8 @@ jobs:
           - build-cache-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
       - run:
           name: Build and test frontend
-          command: ./node_modules/.bin/grafana-toolkit plugin:ci-build
+          command:  |
+            /usr/local/bin/grafana-toolkit plugin:ci-build
       - persist_to_workspace:
           root: .
           paths:
@@ -159,11 +166,14 @@ jobs:
         at: .
     - run:
         name: Move results to ci folder
-        command: ./node_modules/.bin/grafana-toolkit plugin:ci-build --finish
+        command:  |
+          /usr/local/bin/grafana-toolkit plugin:ci-build --finish
     - run:
         name: Package distribution
         command: |
-          ./node_modules/.bin/grafana-toolkit plugin:ci-package
+          # needed for shasum command
+          apk --update-cache add perl-utils
+          /usr/local/bin/grafana-toolkit plugin:ci-package
     - persist_to_workspace:
         root: .
         paths:
@@ -190,7 +200,7 @@ jobs:
           mkdir ci # Avoid error if not exists
           mkdir ci/jobs # Avoid error if not exists
           mkdir ci/jobs/provisioning
-          mv plugin-provisioning/plugins/google-sheets/provisioning/* ci/jobs/provisioning
+          mv plugin-provisioning/plugins/azure-data-explorer-datasource/provisioning/* ci/jobs/provisioning
     - persist_to_workspace:
         root: .
         paths:
@@ -220,7 +230,7 @@ jobs:
           ginstall canary
           /opt/grafana/bin/grafana-server -config ci/grafana-test-env/custom.ini -homepath /opt/grafana &
           ## To make sure grafana has started up
-          while ! $(netstat -tulpn | grep 3000 >/dev/null 2>&1); do sleep 1; done 
+          while ! $(netstat -tulpn | grep 3000 >/dev/null 2>&1); do sleep 1; done
           /opt/grafana/bin/grafana-cli --version
 
     - run:
@@ -265,7 +275,7 @@ jobs:
     - run:
         name: Toolkit report
         command: |
-          ./node_modules/.bin/grafana-toolkit plugin:ci-report
+          /usr/local/bin/grafana-toolkit plugin:ci-report
     - store_artifacts:
         path: ci
 
@@ -275,7 +285,7 @@ jobs:
       - checkout
       - add_ssh_keys:
           fingerprints:
-            - "dc:60:ab:c7:2d:8c:82:50:2a:2a:97:1a:c0:66:83:14"
+          - << pipeline.parameters.ssh-fingerprint >>
       - attach_workspace:
           at: .
       - restore_cache:
@@ -285,5 +295,39 @@ jobs:
       - run:
           name: "Publish Release on GitHub"
           command: |
-            ./node_modules/.bin/grafana-toolkit plugin:github-publish
+            /usr/local/bin/grafana-toolkit plugin:github-publish
 
+  publish_artifacts_to_gcs:
+    executor: cloud_sdk_exec
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: "Copy Artifacts to GCP Bucket"
+          command: |
+            apt update
+            apt install -y jq git-lfs
+            PLUGIN_NAME=`cat ci/dist/plugin.json|jq '.id'| sed s/\"//g`
+            echo "Plugin Name: ${PLUGIN_NAME}"
+            VERSION=`cat ci/dist/plugin.json|jq '.info.version'| sed s/\"//g`
+            echo "Plugin Version: ${VERSION}"
+            # copy
+            if [ -z "${GCLOUD_SERVICE_KEY}" ]; then
+              echo "Missing GCS Publish Key"
+              exit -1
+            fi
+            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
+            echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/${CIRCLE_SHA1}"
+            gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/${CIRCLE_SHA1}
+            echo "Cleaning latest for branch"
+            gsutil rm -f gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/latest/** || true
+            echo "Copying artifacts to ${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/latest"
+            gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${VERSION}/${CIRCLE_BRANCH}/latest
+            # special handling for master
+            if [ ${CIRCLE_BRANCH} == "master" ]; then
+              echo "Cleaning master latest"
+              gsutil rm -f gs://integration-artifacts/${PLUGIN_NAME}/${CIRCLE_BRANCH}/latest/** || true
+              echo "Copying artifacts to master latest"
+              gsutil -m cp -r ci/packages/** gs://integration-artifacts/${PLUGIN_NAME}/${CIRCLE_BRANCH}/latest
+            fi
